name = "LatPhysLatticeConstruction"
uuid = "ec4de012-e8d7-11e8-3fed-dfe576d3bbe4"
authors = ["Jan Attig <jattig@thp.Uni-Koeln.DE>"]
version = "0.1.0"

[deps]
LatPhysBase = "eec5c15a-e8bd-11e8-0d23-6799ca40c963"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
